using System.Collections.Generic;
using System.Diagnostics;
using NSWallet.Shared;
using Xamarin.Forms;

namespace NSWallet.NetStandard.Helpers
{
	public static class IconGroupsHandler
	{
		public static Dictionary<string, string> IconsWithGroups = new Dictionary<string, string> {
			{ "document",  "group_common" },
			{ "accesspoint",  "group_common" },
			{ "airplane",  "group_common" },
			{ "amazon",  "group_stores" },
			{ "americanexpress",  "group_finances" },
			{ "apple",  "group_technology" },
			{ "aspirin",  "group_medicine" },
			{ "badoo",  "group_social" },
			{ "banking",  "group_finances" },
			{ "bitcoin",  "group_finances" },
			{ "blackberry",  "group_technology" },
			{ "blogger",  "group_social" },
			{ "book",  "group_common" },
			{ "calendar",  "group_common" },
			{ "cd",  "group_common" },
			{ "chrome",  "group_internet" },
			{ "clock",  "group_common" },
			{ "coins",  "group_finances" },
			{ "comp",  "group_technology" },
			{ "comp2",  "group_technology" },
			{ "comp3",  "group_technology" },
			{ "compass",  "group_common" },
			{ "corona",  "group_technology" },
			{ "cp",  "group_technology" },
			{ "dollar",  "group_finances" },
			{ "droid",  "group_technology" },
			{ "dropbox",  "group_clouds" },
			{ "earth",  "group_common" },
			{ "earth2",  "group_common" },
			{ "ebay",  "group_stores" },
			{ "ebook",  "group_technology" },
			{ "euro",  "group_finances" },
			{ "evernote",  "group_" },
			{ "exchange",  "group_" },
			{ "facebook",  "group_" },
			{ "firefox",  "group_" },
			{ "fireman",  "group_" },
			{ "firstaid",  "group_" },
			{ "flag",  "group_" },
			{ "forpdaru",  "group_" },
			{ "gameloft",  "group_" },
			{ "gift",  "group_" },
			{ "giftcard",  "group_" },
			{ "giftcard2",  "group_" },
			{ "gmail",  "group_" },
			{ "googlecheckout",  "group_" },
			{ "googledrive",  "group_" },
			{ "gplay",  "group_" },
			{ "gplus",  "group_" },
			{ "gtalk",  "group_" },
			{ "heart",  "group_" },
			{ "helicopter",  "group_" },
			{ "home",  "group_" },
			{ "hostgator",  "group_" },
			{ "hrs",  "group_" },
			{ "icq",  "group_" },
			{ "info",  "group_" },
			{ "instg",  "group_" },
			{ "ipad",  "group_" },
			{ "ipad2",  "group_" },
			{ "ipad3",  "group_" },
			{ "iphone",  "group_" },
			{ "iphone2",  "group_" },
			{ "iphone3",  "group_" },
			{ "key",  "group_" },
			{ "key2",  "group_" },
			{ "kinopoisk",  "group_" },
			{ "lingualeo",  "group_" },
			{ "linkedin",  "group_" },
			{ "linux1",  "group_" },
			{ "linux2",  "group_" },
			{ "live",  "group_" },
			{ "lj",  "group_" },
			{ "lock",  "group_" },
			{ "mac",  "group_" },
			{ "maestro",  "group_" },
			{ "mail3",  "group_" },
			{ "mailbox",  "group_" },
			{ "mastercard",  "group_" },
			{ "medical",  "group_" },
			{ "milesmore",  "group_" },
			{ "money",  "group_" },
			{ "money2",  "group_" },
			{ "oovoo",  "group_" },
			{ "passport",  "group_" },
			{ "paypal",  "group_" },
			{ "pencil",  "group_" },
			{ "phone1",  "group_" },
			{ "phone2",  "group_" },
			{ "phone3",  "group_" },
			{ "phone4",  "group_" },
			{ "phone5",  "group_" },
			{ "picasa",  "group_" },
			{ "pocket",  "group_" },
			{ "police",  "group_" },
			{ "psp",  "group_" },
			{ "owncloud",  "group_" },
			{ "redcar",  "group_" },
			{ "rss",  "group_" },
			{ "safe",  "group_" },
			{ "satellitedish",  "group_" },
			{ "securitye",  "group_" },
			{ "securityq",  "group_" },
			{ "server",  "group_" },
			{ "settings",  "group_" },
			{ "skydrive",  "group_" },
			{ "skype",  "group_" },
			{ "sportcar",  "group_" },
			{ "steam",  "group_" },
			{ "stick",  "group_" },
			{ "surfingbird",  "group_" },
			{ "sync",  "group_" },
			{ "taxi",  "group_" },
			{ "teamviewer",  "group_" },
			{ "terminal",  "group_" },
			{ "truck",  "group_" },
			{ "truecrypt",  "group_" },
			{ "tune",  "group_" },
			{ "twitter",  "group_" },
			{ "ubuntu",  "group_" },
			{ "unfuddle",  "group_" },
			{ "user",  "group_" },
			{ "utorrent",  "group_" },
			{ "vacation",  "group_" },
			{ "vimeo",  "group_" },
			{ "visa",  "group_" },
			{ "visadebit",  "group_" },
			{ "visaelectron",  "group_" },
			{ "vkontakte",  "group_" },
			{ "wall",  "group_" },
			{ "whitecar",  "group_" },
			{ "wiki",  "group_" },
			{ "win",  "group_" },
			{ "windows",  "group_" },
			{ "wireless",  "group_" },
			{ "wmk",  "group_" },
			{ "wmlogo",  "group_" },
			{ "wordpress",  "group_" },
			{ "xcode",  "group_" },
			{ "xmarks",  "group_" },
			{ "yahoo",  "group_mail" },
			{ "yandex",  "group_mail" },
			{ "youtube",  "group_media" }
		};

		public static int CountGroups()
		{
			var groupList = new List<string>();
			int counter = 0;
			foreach (var icon in IconsWithGroups) {
				var group = groupList.Find(x => x == icon.Value);
				if(group == null) {
					groupList.Add(icon.Value);
					counter++;
				}
			}
			return counter;
		}
	}
}